[package]
name = "microcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
microwfc = "0.5"
rand = "0.8"
rand_chacha = "0.3"
colorful = "0.2"